# Use an official Node.js image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy application files
COPY . .

# Expose the port app runs on
EXPOSE 3002

# Start the server
CMD ["node", "server.js"]
